version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@1.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - eb/setup
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run:
                name: Deploying
                command: |
                  eb use Nodeapp-env
                  eb deploy Nodeapp-env

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context: aws
          filters:
            branches:
              only:
                - master
